
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusquedasServiceService", targetNamespace = "http://webservices.espotify/", wsdlLocation = "http://localhost:8089/BusquedasService?wsdl")
public class BusquedasServiceService
    extends Service
{

    private final static URL BUSQUEDASSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSQUEDASSERVICESERVICE_EXCEPTION;
    private final static QName BUSQUEDASSERVICESERVICE_QNAME = new QName("http://webservices.espotify/", "BusquedasServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/BusquedasService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSQUEDASSERVICESERVICE_WSDL_LOCATION = url;
        BUSQUEDASSERVICESERVICE_EXCEPTION = e;
    }

    public BusquedasServiceService() {
        super(__getWsdlLocation(), BUSQUEDASSERVICESERVICE_QNAME);
    }

    public BusquedasServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSQUEDASSERVICESERVICE_QNAME, features);
    }

    public BusquedasServiceService(URL wsdlLocation) {
        super(wsdlLocation, BUSQUEDASSERVICESERVICE_QNAME);
    }

    public BusquedasServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSQUEDASSERVICESERVICE_QNAME, features);
    }

    public BusquedasServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusquedasServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusquedasService
     */
    @WebEndpoint(name = "BusquedasServicePort")
    public BusquedasService getBusquedasServicePort() {
        return super.getPort(new QName("http://webservices.espotify/", "BusquedasServicePort"), BusquedasService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusquedasService
     */
    @WebEndpoint(name = "BusquedasServicePort")
    public BusquedasService getBusquedasServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.espotify/", "BusquedasServicePort"), BusquedasService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSQUEDASSERVICESERVICE_EXCEPTION!= null) {
            throw BUSQUEDASSERVICESERVICE_EXCEPTION;
        }
        return BUSQUEDASSERVICESERVICE_WSDL_LOCATION;
    }

}
