
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContenidoServiceService", targetNamespace = "http://webservices.espotify/", wsdlLocation = "http://localhost:8089/ContenidoService?wsdl")
public class ContenidoServiceService
    extends Service
{

    private final static URL CONTENIDOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTENIDOSERVICESERVICE_EXCEPTION;
    private final static QName CONTENIDOSERVICESERVICE_QNAME = new QName("http://webservices.espotify/", "ContenidoServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/ContenidoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTENIDOSERVICESERVICE_WSDL_LOCATION = url;
        CONTENIDOSERVICESERVICE_EXCEPTION = e;
    }

    public ContenidoServiceService() {
        super(__getWsdlLocation(), CONTENIDOSERVICESERVICE_QNAME);
    }

    public ContenidoServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTENIDOSERVICESERVICE_QNAME, features);
    }

    public ContenidoServiceService(URL wsdlLocation) {
        super(wsdlLocation, CONTENIDOSERVICESERVICE_QNAME);
    }

    public ContenidoServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTENIDOSERVICESERVICE_QNAME, features);
    }

    public ContenidoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContenidoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContenidoService
     */
    @WebEndpoint(name = "ContenidoServicePort")
    public ContenidoService getContenidoServicePort() {
        return super.getPort(new QName("http://webservices.espotify/", "ContenidoServicePort"), ContenidoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContenidoService
     */
    @WebEndpoint(name = "ContenidoServicePort")
    public ContenidoService getContenidoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.espotify/", "ContenidoServicePort"), ContenidoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTENIDOSERVICESERVICE_EXCEPTION!= null) {
            throw CONTENIDOSERVICESERVICE_EXCEPTION;
        }
        return CONTENIDOSERVICESERVICE_WSDL_LOCATION;
    }

}
