
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */

@WebService(name = "ListasReproduccionService", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListasReproduccionService {

    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/getNombresListasParticularesRequest", output = "http://webservices/ListasReproduccionService/getNombresListasParticularesResponse")
    public MyArrayList getNombresListasParticulares();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/getListaDTDatosListaReproduccionDeClienteRequest", output = "http://webservices/ListasReproduccionService/getListaDTDatosListaReproduccionDeClienteResponse")
    public MyArrayList getListaDTDatosListaReproduccionDeCliente(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "CrearListaParticularConFecha")
    @Action(input = "http://webservices/ListasReproduccionService/CrearListaParticularConFechaRequest", output = "http://webservices/ListasReproduccionService/CrearListaParticularConFechaResponse")
    public void crearListaParticularConFecha(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        boolean arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "CrearListaParticular")
    @Action(input = "http://webservices/ListasReproduccionService/CrearListaParticularRequest", output = "http://webservices/ListasReproduccionService/CrearListaParticularResponse")
    public void crearListaParticular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        boolean arg3);

    /**
     * 
     * @return
     *     returns webservices.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/getNombresListasPorDefectoRequest", output = "http://webservices/ListasReproduccionService/getNombresListasPorDefectoResponse")
    public MyArrayList getNombresListasPorDefecto();

    /**
     * 
     * @return
     *     returns webservices.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/getNombresListasParticularesPublicasRequest", output = "http://webservices/ListasReproduccionService/getNombresListasParticularesPublicasResponse")
    public MyArrayList getNombresListasParticularesPublicas();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns webservices.DtDatosListaReproduccion
     */
    @WebMethod(operationName = "ConsultarListaReproduccion")
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/ConsultarListaReproduccionRequest", output = "http://webservices/ListasReproduccionService/ConsultarListaReproduccionResponse")
    public DtDatosListaReproduccion consultarListaReproduccion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns webservices.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/getListasReproduccionDisponiblesRequest", output = "http://webservices/ListasReproduccionService/getListasReproduccionDisponiblesResponse")
    public MyArrayList getListasReproduccionDisponibles();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/ListasReproduccionService/listasCreadasEstadoPrivadoTrueRequest", output = "http://webservices/ListasReproduccionService/listasCreadasEstadoPrivadoTrueResponse")
    public MyArrayList listasCreadasEstadoPrivadoTrue(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
