
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PreferenciasServiceService", targetNamespace = "http://webservices.espotify/", wsdlLocation = "http://localhost:8089/PreferenciasService?wsdl")
public class PreferenciasServiceService
    extends Service
{

    private final static URL PREFERENCIASSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PREFERENCIASSERVICESERVICE_EXCEPTION;
    private final static QName PREFERENCIASSERVICESERVICE_QNAME = new QName("http://webservices.espotify/", "PreferenciasServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/PreferenciasService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREFERENCIASSERVICESERVICE_WSDL_LOCATION = url;
        PREFERENCIASSERVICESERVICE_EXCEPTION = e;
    }

    public PreferenciasServiceService() {
        super(__getWsdlLocation(), PREFERENCIASSERVICESERVICE_QNAME);
    }

    public PreferenciasServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREFERENCIASSERVICESERVICE_QNAME, features);
    }

    public PreferenciasServiceService(URL wsdlLocation) {
        super(wsdlLocation, PREFERENCIASSERVICESERVICE_QNAME);
    }

    public PreferenciasServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREFERENCIASSERVICESERVICE_QNAME, features);
    }

    public PreferenciasServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreferenciasServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PreferenciasService
     */
    @WebEndpoint(name = "PreferenciasServicePort")
    public PreferenciasService getPreferenciasServicePort() {
        return super.getPort(new QName("http://webservices.espotify/", "PreferenciasServicePort"), PreferenciasService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PreferenciasService
     */
    @WebEndpoint(name = "PreferenciasServicePort")
    public PreferenciasService getPreferenciasServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.espotify/", "PreferenciasServicePort"), PreferenciasService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREFERENCIASSERVICESERVICE_EXCEPTION!= null) {
            throw PREFERENCIASSERVICESERVICE_EXCEPTION;
        }
        return PREFERENCIASSERVICESERVICE_WSDL_LOCATION;
    }

}
