
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;
import java.util.Date;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistroService", targetNamespace = "http://webservices.espotify/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RegistroService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices.espotify/RegistroService/guardarRegistroAccesoRequest", output = "http://webservices.espotify/RegistroService/guardarRegistroAccesoResponse")
    public void guardarRegistroAcceso(
        @WebParam(name = "arg0", partName = "arg0")
                String arg0, @WebParam(name = "arg1", partName = "arg1")
                        String arg1, @WebParam(name = "arg2", partName = "arg2")
                                String arg2, @WebParam(name = "arg3", partName = "arg3")
                                        String arg3, @WebParam(name = "arg4", partName = "arg4")
    Date arg4);

}
