package espotify.presentacion;

import espotify.DataTypes.DTAlbum_Simple;
import espotify.logica.Fabrica;
import espotify.logica.IControlador;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author mat
 */
public class AgregarTemaALista extends javax.swing.JInternalFrame {

    private IControlador controlador;
    private DefaultListModel listaDeListasModel;
    private DefaultListModel listaDeListasOAlbumsModel;
    private DefaultListModel listaDeTemasModel;
    
    private List<String> nicknamesClientes;
    private List<String> listaNombresDeListasGenericas;
    private List<String> listaNombresListasParticularesPublicas;
    private List<String> listaNombresListasPorDefecto;
    private List<String> listaDatosAlbums;
    private List<String> listaDatosTemas;
    private Map<Long, String> mapAlbums;
    private Map<Long, String> mapTemas;
    private List<DTAlbum_Simple> listaDeDTAlbums;
    /**
     * Creates new form AgregarTemaALista
     */
    public AgregarTemaALista() {
        Fabrica fb = Fabrica.getInstance();
        controlador = fb.getControlador();
        nicknamesClientes = controlador.getNicknamesClientes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        comboBoxTipoLista = new javax.swing.JComboBox<>();
        btnConfirmarAgregarTemaALista = new javax.swing.JButton();
        btnCancelarAgregarTemaALista = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxTipoDeOrigenTema = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeListasOAlbumsModel = new DefaultListModel();
        jlistOrigenDeTema = new javax.swing.JList(listaDeListasOAlbumsModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeTemasModel = new DefaultListModel();
        listaDeTemas = new javax.swing.JList(listaDeTemasModel);
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDeListasModel = new DefaultListModel();
        jlistListasReproduccion = new javax.swing.JList(listaDeListasModel);
        jLabel4 = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboBoxClientes = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Tema a Lista de Reproducción");

        jLabel5.setText("Tipo de lista: ");

        comboBoxTipoLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Lista por defecto", "Lista particular" }));
        comboBoxTipoLista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTipoListaItemStateChanged(evt);
            }
        });
        comboBoxTipoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoListaActionPerformed(evt);
            }
        });
        comboBoxTipoLista.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboBoxTipoListaPropertyChange(evt);
            }
        });

        btnConfirmarAgregarTemaALista.setText("Confirmar");
        btnConfirmarAgregarTemaALista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarAgregarTemaAListaActionPerformed(evt);
            }
        });

        btnCancelarAgregarTemaALista.setText("Cancelar");
        btnCancelarAgregarTemaALista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAgregarTemaAListaActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione la lista a la cual agregar el tema y el usuario si corresponde:");

        jLabel7.setText("Elija de donde seleccionar tema que desea agregar:");

        comboBoxTipoDeOrigenTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Lista por defecto", "Lista particular", "Album" }));
        comboBoxTipoDeOrigenTema.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTipoDeOrigenTemaItemStateChanged(evt);
            }
        });
        comboBoxTipoDeOrigenTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoDeOrigenTemaActionPerformed(evt);
            }
        });

        jLabel9.setText("Origen:");

        jlistOrigenDeTema.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistOrigenDeTema.setEnabled(false);
        jScrollPane1.setViewportView(jlistOrigenDeTema);

        listaDeTemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaDeTemas);

        jLabel10.setText("Tema:");

        jLabel3.setText("Seleccione el tema que desea agregar:");

        jlistListasReproduccion.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jlistListasReproduccion);

        jLabel4.setText("Clientes:");

        labelError.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("jButton1");

        String[] arrayNicknamesClientes = nicknamesClientes.toArray(new String[nicknamesClientes.size()]);
        comboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(arrayNicknamesClientes));
        comboBoxClientes.setToolTipText("");
        comboBoxClientes.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnCancelarAgregarTemaALista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfirmarAgregarTemaALista, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(236, 236, 236))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTipoDeOrigenTema, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jScrollPane2))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBoxTipoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(9, 9, 9))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxTipoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboBoxTipoDeOrigenTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarAgregarTemaALista)
                    .addComponent(btnCancelarAgregarTemaALista))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxTipoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTipoListaActionPerformed

    private void comboBoxTipoListaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboBoxTipoListaPropertyChange
        //
    }//GEN-LAST:event_comboBoxTipoListaPropertyChange

    private void btnCancelarAgregarTemaAListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAgregarTemaAListaActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarAgregarTemaAListaActionPerformed

    private void comboBoxTipoListaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTipoListaItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            if (comboBoxTipoLista.getSelectedItem().toString().equals("Lista particular")) {
                
                jlistListasReproduccion.setEnabled(true);
                comboBoxClientes.setEnabled(true);
                
                listaNombresDeListasGenericas = controlador.getNombresListasParticulares();
                for (String nombreLista : listaNombresDeListasGenericas) {
                    listaDeListasModel.addElement(nombreLista);
                }
                jlistListasReproduccion.setModel(listaDeListasModel);
                
            } else if (comboBoxTipoLista.getSelectedItem().toString().equals("Lista por defecto")){
                
                jlistListasReproduccion.setEnabled(true);
                comboBoxClientes.setEnabled(false);
                
                listaNombresDeListasGenericas = controlador.getNombresListasPorDefecto();
                for (String nombreLista : listaNombresDeListasGenericas) {
                    listaDeListasModel.addElement(nombreLista);
                }
                jlistListasReproduccion.setModel(listaDeListasModel);
                
            } else {
                comboBoxClientes.setEnabled(false);
                jlistListasReproduccion.setEnabled(false);
            }
        }
    }//GEN-LAST:event_comboBoxTipoListaItemStateChanged

    private void comboBoxTipoDeOrigenTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoDeOrigenTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTipoDeOrigenTemaActionPerformed

    private void btnConfirmarAgregarTemaAListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarAgregarTemaAListaActionPerformed
        
    }//GEN-LAST:event_btnConfirmarAgregarTemaAListaActionPerformed

    private void comboBoxTipoDeOrigenTemaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTipoDeOrigenTemaItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            if (comboBoxTipoLista.getSelectedItem().toString().equals("Lista particular")) {
                
                //habilito la seleccion del jlist
                jlistOrigenDeTema.setEnabled(true);
                //obtengo las listas particulares publicas
                listaNombresListasParticularesPublicas = controlador.getListasReproduccionDisponibles();
                //las cargo en el jlist por medio del list model
                for (String nombreLista : listaNombresListasParticularesPublicas) {
                    listaDeListasOAlbumsModel.addElement(nombreLista);
                }
                jlistOrigenDeTema.setModel(listaDeListasOAlbumsModel);
                
            } else if (comboBoxTipoLista.getSelectedItem().toString().equals("Lista por defecto")) {
                jlistOrigenDeTema.setEnabled(true);
                listaNombresListasPorDefecto = controlador.getNombresListasPorDefecto();
                
                for (String nombreLista : listaNombresListasPorDefecto) {
                    listaDeListasOAlbumsModel.addElement(nombreLista);
                }
                jlistOrigenDeTema.setModel(listaDeListasOAlbumsModel);
                
            } else if (comboBoxTipoLista.getSelectedItem().toString().equals("Album")) {
                jlistOrigenDeTema.setEnabled(true);
                listaDeDTAlbums = controlador.getDTAlbumesSimple();
                mapAlbums = new HashMap<Long, String>(listaDeDTAlbums.size());
                
                for (DTAlbum_Simple dtAlbum : listaDeDTAlbums) {
                    mapAlbums.put(dtAlbum.getIdAlbum(), dtAlbum.toStringSimple());
                }
                
                
            } else {
                jlistOrigenDeTema.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_comboBoxTipoDeOrigenTemaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAgregarTemaALista;
    private javax.swing.JButton btnConfirmarAgregarTemaALista;
    private javax.swing.JComboBox<String> comboBoxClientes;
    private javax.swing.JComboBox<String> comboBoxTipoDeOrigenTema;
    private javax.swing.JComboBox<String> comboBoxTipoLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> jlistListasReproduccion;
    private javax.swing.JList<String> jlistOrigenDeTema;
    private javax.swing.JLabel labelError;
    private javax.swing.JList<String> listaDeTemas;
    // End of variables declaration//GEN-END:variables
}
