package espotify.presentacion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author ms
 */
public class ConsultaListaReproduccion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultadeListadeReproduccion
     */
    public ConsultaListaReproduccion() {
        initComponents();
        jLabelListaDeGeneros.setVisible(true);
        jListListaDeGeneros.setVisible(true);
        jScrollPaneGenero.setVisible(true);
        jLabelGenero.setVisible(true);
        jTextFieldGenero.setVisible(true);
        
        
        jLabelListaDeArtistas.setVisible(false);
        jListListarDeArtistas.setVisible(false);
        JScrollPanelArtista.setVisible(false);
        jLabelCliente.setVisible(false);
        jTextFieldCliente.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelConsultarPor = new javax.swing.JLabel();
        jComboBoxConsultarPor = new javax.swing.JComboBox<>();
        jLabelListaDeGeneros = new javax.swing.JLabel();
        jLabelListaDeArtistas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JScrollPanelArtista = new javax.swing.JScrollPane();
        jListListarDeArtistas = new javax.swing.JList<>();
        jScrollPaneGenero = new javax.swing.JScrollPane();
        jListListaDeGeneros = new javax.swing.JList<>();
        jLabelListasDeReproduccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListaDeReproduccion = new javax.swing.JList<>();
        jLabelNombreDeLaLista = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelInformacionDeLosTemas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInformacionDeLosTemas = new javax.swing.JTextArea();
        jTextFieldCliente = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        jButtonDescargarArchivosDeMusica = new javax.swing.JButton();
        jButtonVerDireccionWeb = new javax.swing.JButton();
        jTextFieldNombreDeLaLista = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Lista de Reproduccion");

        jLabelConsultarPor.setText("Consultar por: ");

        jComboBoxConsultarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Género", "Cliente" }));
        jComboBoxConsultarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsultarPorActionPerformed(evt);
            }
        });

        jLabelListaDeGeneros.setText("Lista de Géneros:");

        jLabelListaDeArtistas.setText("Lista de Artistas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jListListarDeArtistas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Artista 1", "Artista 2", "Artista 3", "Artista 4", "Artista 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JScrollPanelArtista.setViewportView(jListListarDeArtistas);

        jListListaDeGeneros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Género 1", "Género 2", "Género 3", "Género 4", "Género 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneGenero.setViewportView(jListListaDeGeneros);

        jLabelListasDeReproduccion.setText("Listas de Reproducción:");

        jListListaDeReproduccion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista 1", "Lista 2", "Lista 3", "Lista 4", "Lista 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListListaDeReproduccion);

        jLabelNombreDeLaLista.setText("Nombre de la Lista:");

        jLabelGenero.setText("Género:");

        jLabelCliente.setText("Cliente:");

        jLabelInformacionDeLosTemas.setText("Información de los temas:");

        jTextAreaInformacionDeLosTemas.setColumns(20);
        jTextAreaInformacionDeLosTemas.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInformacionDeLosTemas);

        jTextFieldCliente.setText("Juan Jose");
        jTextFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteActionPerformed(evt);
            }
        });

        jTextFieldGenero.setText("Rock Nacional");
        jTextFieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGeneroActionPerformed(evt);
            }
        });

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonDescargarArchivosDeMusica.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonDescargarArchivosDeMusica.setText("Descargar Archivo de Música");
        jButtonDescargarArchivosDeMusica.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonVerDireccionWeb.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButtonVerDireccionWeb.setText("Ver Dirección Web");
        jButtonVerDireccionWeb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldNombreDeLaLista.setText("Canciones de Rock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelConsultarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxConsultarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelListaDeGeneros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelListaDeArtistas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPaneGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JScrollPanelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelListasDeReproduccion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelNombreDeLaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldNombreDeLaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelCliente)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelGenero)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldGenero)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelInformacionDeLosTemas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDescargarArchivosDeMusica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVerDireccionWeb)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultarPor)
                    .addComponent(jComboBoxConsultarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombreDeLaLista)
                                    .addComponent(jTextFieldNombreDeLaLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGenero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCliente)
                                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15)
                        .addComponent(jLabelInformacionDeLosTemas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDescargarArchivosDeMusica)
                            .addComponent(jButtonVerDireccionWeb)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelListaDeGeneros)
                            .addComponent(jLabelListaDeArtistas)
                            .addComponent(jLabelListasDeReproduccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JScrollPanelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxConsultarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsultarPorActionPerformed
        String opcion=(String)jComboBoxConsultarPor.getSelectedItem();
        if(opcion=="Género"){
            jLabelListaDeGeneros.setVisible(true);
            jListListaDeGeneros.setVisible(true);
            jScrollPaneGenero.setVisible(true);
            jLabelGenero.setVisible(true);
            jTextFieldGenero.setVisible(true);
            
            jLabelListaDeArtistas.setVisible(false);
            jListListarDeArtistas.setVisible(false);
            JScrollPanelArtista.setVisible(false);
            jLabelCliente.setVisible(false);
            jTextFieldCliente.setVisible(false);
            
        }
        else{
            jLabelListaDeGeneros.setVisible(false);
            jListListaDeGeneros.setVisible(false);
            jScrollPaneGenero.setVisible(false);
            jLabelGenero.setVisible(false);
            jTextFieldGenero.setVisible(false);
            
            
            jLabelListaDeArtistas.setVisible(true);
            jListListarDeArtistas.setVisible(true);
            JScrollPanelArtista.setVisible(true);
            jLabelCliente.setVisible(true);
            jTextFieldCliente.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxConsultarPorActionPerformed

    private void jTextFieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGeneroActionPerformed

    private void jTextFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanelArtista;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButtonDescargarArchivosDeMusica;
    private javax.swing.JButton jButtonVerDireccionWeb;
    private javax.swing.JComboBox<String> jComboBoxConsultarPor;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelConsultarPor;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelInformacionDeLosTemas;
    private javax.swing.JLabel jLabelListaDeArtistas;
    private javax.swing.JLabel jLabelListaDeGeneros;
    private javax.swing.JLabel jLabelListasDeReproduccion;
    private javax.swing.JLabel jLabelNombreDeLaLista;
    private javax.swing.JList<String> jListListaDeGeneros;
    private javax.swing.JList<String> jListListaDeReproduccion;
    private javax.swing.JList<String> jListListarDeArtistas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneGenero;
    private javax.swing.JTextArea jTextAreaInformacionDeLosTemas;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombreDeLaLista;
    // End of variables declaration//GEN-END:variables
}
