/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package espotify.presentacion;

/**
 *
 * @author tecnologo
 */
public class ConsultaPerfilCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaPerfilCliente
     */
    public ConsultaPerfilCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSeleccioneCliente = new javax.swing.JLabel();
        jScrollPaneListClientes = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabelNickname = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelFecNac = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        ImageClienteLabel = new javax.swing.JLabel();
        LabelNicknameInfo = new javax.swing.JLabel();
        jLabelNombreInfo = new javax.swing.JLabel();
        jLabelApellidoInfo = new javax.swing.JLabel();
        jLabelFecNacInfo = new javax.swing.JLabel();
        jLabelCorreoInfo = new javax.swing.JLabel();
        jLabelTituloDatos = new javax.swing.JLabel();
        jLabelTituloSeguidores = new javax.swing.JLabel();
        jLabelTituloSeguidos = new javax.swing.JLabel();
        jLabelTituloListasReproduccion = new javax.swing.JLabel();
        jLabelTituloListasFavoritas = new javax.swing.JLabel();
        jLabelTituloListasCreadas = new javax.swing.JLabel();
        jScrollPaneSeguidores = new javax.swing.JScrollPane();
        jListSeguidores = new javax.swing.JList<>();
        jScrollPaneSeguidos = new javax.swing.JScrollPane();
        jListSeguidos = new javax.swing.JList<>();
        jScrollPaneListasRCreadas = new javax.swing.JScrollPane();
        jListListasRCreadas = new javax.swing.JList<>();
        jScrollPaneListasRFavoritas = new javax.swing.JScrollPane();
        jListListasRFavoritas = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Perfil de Cliente");
        setPreferredSize(new java.awt.Dimension(1150, 600));

        jLabelSeleccioneCliente.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelSeleccioneCliente.setText("SELECCIONE UN CLIENTE");

        jListClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListClientes.setViewportView(jListClientes);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelNickname.setText("Nickname:");

        jLabelNombre.setText("Nombre:");

        jLabelApellido.setText("Apellido:");

        jLabelFecNac.setText("Fecha de nacimiento:");

        jLabelCorreo.setText("Correo electronico:");

        ImageClienteLabel.setText("Foto de Perfil");

        LabelNicknameInfo.setText("alex1");

        jLabelNombreInfo.setText("Alex");

        jLabelApellidoInfo.setText("Smith");

        jLabelFecNacInfo.setText("11/12/1978");

        jLabelCorreoInfo.setText("alex.smith@gmail.com");

        jLabelTituloDatos.setFont(new java.awt.Font("Liberation Sans", 1, 21)); // NOI18N
        jLabelTituloDatos.setText("DATOS DEL CLIENTE");

        jLabelTituloSeguidores.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloSeguidores.setText("SEGUIDORES");

        jLabelTituloSeguidos.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloSeguidos.setText("SEGUIDOS");

        jLabelTituloListasReproduccion.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloListasReproduccion.setText("LISTAS DE REPRODUCCION");

        jLabelTituloListasFavoritas.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloListasFavoritas.setText("FAVORITAS");

        jLabelTituloListasCreadas.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloListasCreadas.setText("CREADAS");

        jListSeguidores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSeguidores.setViewportView(jListSeguidores);

        jListSeguidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSeguidos.setViewportView(jListSeguidos);

        jListListasRCreadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListasRCreadas.setViewportView(jListListasRCreadas);

        jListListasRFavoritas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListasRFavoritas.setViewportView(jListListasRFavoritas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSeleccioneCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAceptar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelTituloListasCreadas)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabelTituloListasFavoritas)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPaneSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneSeguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107)
                                        .addComponent(jScrollPaneListasRCreadas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPaneListasRFavoritas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTituloListasReproduccion)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(293, 293, 293)
                                        .addComponent(jLabelTituloDatos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabelTituloSeguidores)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabelTituloSeguidos)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(ImageClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFecNac)
                                    .addComponent(jLabelNickname)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jLabelCorreo))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelNicknameInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNombreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelApellidoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelFecNacInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCorreoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelSeleccioneCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTituloDatos)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNickname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelNicknameInfo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabelNombreInfo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelApellido)
                                    .addComponent(jLabelApellidoInfo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFecNac)
                                    .addComponent(jLabelFecNacInfo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCorreo)
                                    .addComponent(jLabelCorreoInfo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ImageClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabelTituloListasReproduccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTituloListasFavoritas)
                            .addComponent(jLabelTituloListasCreadas)
                            .addComponent(jLabelTituloSeguidos)
                            .addComponent(jLabelTituloSeguidores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneSeguidores)
                            .addComponent(jScrollPaneListasRCreadas)
                            .addComponent(jScrollPaneSeguidos)
                            .addComponent(jScrollPaneListasRFavoritas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageClienteLabel;
    private javax.swing.JLabel LabelNicknameInfo;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellidoInfo;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCorreoInfo;
    private javax.swing.JLabel jLabelFecNac;
    private javax.swing.JLabel jLabelFecNacInfo;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreInfo;
    private javax.swing.JLabel jLabelSeleccioneCliente;
    private javax.swing.JLabel jLabelTituloDatos;
    private javax.swing.JLabel jLabelTituloListasCreadas;
    private javax.swing.JLabel jLabelTituloListasFavoritas;
    private javax.swing.JLabel jLabelTituloListasReproduccion;
    private javax.swing.JLabel jLabelTituloSeguidores;
    private javax.swing.JLabel jLabelTituloSeguidos;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListListasRCreadas;
    private javax.swing.JList<String> jListListasRFavoritas;
    private javax.swing.JList<String> jListSeguidores;
    private javax.swing.JList<String> jListSeguidos;
    private javax.swing.JScrollPane jScrollPaneListClientes;
    private javax.swing.JScrollPane jScrollPaneListasRCreadas;
    private javax.swing.JScrollPane jScrollPaneListasRFavoritas;
    private javax.swing.JScrollPane jScrollPaneSeguidores;
    private javax.swing.JScrollPane jScrollPaneSeguidos;
    // End of variables declaration//GEN-END:variables
}
