/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package espotify.presentacion;

import espotify.DataTypes.DTDatosCliente;
import espotify.logica.Fabrica;
import espotify.logica.IControlador;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author tecnologo
 */
public class ConsultaPerfilCliente extends javax.swing.JInternalFrame {

    IControlador controlador;
    
    public ConsultaPerfilCliente() {
        initComponents();
        
        Fabrica fb = Fabrica.getInstance();
        controlador = fb.getControlador();
        
        InicializarJLists();
        
        /* Cargo el jList con los Nicknames de Clientes del Sistema */
        DefaultListModel<String> listaNicknamesClientes = new DefaultListModel<>();
        ArrayList<String> nicknamesClientes = new ArrayList<>(controlador.getNicknamesClientes());
        
        for (String nickname: nicknamesClientes) {
            listaNicknamesClientes.addElement(nickname);
        }
        jListClientes.setModel(listaNicknamesClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSeleccioneCliente = new javax.swing.JLabel();
        jScrollPaneListClientes = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jButtonAceptar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel = new javax.swing.JPanel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelFecNacInfo = new javax.swing.JLabel();
        jLabelNicknameInfo = new javax.swing.JLabel();
        ImageClienteLabel = new javax.swing.JLabel();
        jLabelCorreoInfo = new javax.swing.JLabel();
        jLabelTituloSeguidos = new javax.swing.JLabel();
        jLabelFecNac = new javax.swing.JLabel();
        jLabelTituloListasCreadas = new javax.swing.JLabel();
        jScrollPaneSeguidos = new javax.swing.JScrollPane();
        jListSeguidos = new javax.swing.JList<>();
        jScrollPaneListasRFavoritas = new javax.swing.JScrollPane();
        jListListasRFavoritas = new javax.swing.JList<>();
        jLabelNombreInfo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTituloSeguidores = new javax.swing.JLabel();
        jLabelApellidoInfo = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jScrollPaneSeguidores = new javax.swing.JScrollPane();
        jListSeguidores = new javax.swing.JList<>();
        jLabelNickname = new javax.swing.JLabel();
        jScrollPaneListasRCreadas = new javax.swing.JScrollPane();
        jListListasRCreadas = new javax.swing.JList<>();
        jLabel = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabelTituloListasFavoritas = new javax.swing.JLabel();
        jLabelTituloAlbumesFavoritos = new javax.swing.JLabel();
        jLabelTituloTemasFavoritos = new javax.swing.JLabel();
        jScrollPaneTemasFavoritos = new javax.swing.JScrollPane();
        jListTemasFavoritos = new javax.swing.JList<>();
        jScrollPaneAlbumesFavoritos = new javax.swing.JScrollPane();
        jListAlbumesFavoritos = new javax.swing.JList<>();
        jLabelTituloDatos = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Perfil de Cliente");
        setPreferredSize(new java.awt.Dimension(1150, 600));

        jLabelSeleccioneCliente.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelSeleccioneCliente.setText("SELECCIONE UN CLIENTE");

        jListClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListClientes.setViewportView(jListClientes);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabelCorreo.setText("Correo electronico:");

        jLabelFecNacInfo.setText("...");

        jLabelNicknameInfo.setText("...");

        ImageClienteLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCorreoInfo.setText("...");

        jLabelTituloSeguidos.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloSeguidos.setText("SEGUIDOS");

        jLabelFecNac.setText("Fecha de nacimiento:");

        jLabelTituloListasCreadas.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloListasCreadas.setText("LISTAS CREADAS");

        jListSeguidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSeguidos.setViewportView(jListSeguidos);

        jListListasRFavoritas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListasRFavoritas.setViewportView(jListListasRFavoritas);

        jLabelNombreInfo.setText("...");

        jLabelNombre.setText("Nombre:");

        jLabelTituloSeguidores.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloSeguidores.setText("SEGUIDORES");

        jLabelApellidoInfo.setText("...");

        jLabelApellido.setText("Apellido:");

        jListSeguidores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSeguidores.setViewportView(jListSeguidores);

        jLabelNickname.setText("Nickname:");

        jListListasRCreadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListasRCreadas.setViewportView(jListListasRCreadas);

        jLabel.setFont(new java.awt.Font("Liberation Sans", 3, 15)); // NOI18N
        jLabel.setText("PREFERENCIAS");

        jLabelTituloListasFavoritas.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloListasFavoritas.setText("LISTAS FAVORITAS");

        jLabelTituloAlbumesFavoritos.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloAlbumesFavoritos.setText("ALBUMES FAVORITOS");

        jLabelTituloTemasFavoritos.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabelTituloTemasFavoritos.setText("TEMAS FAVORITOS");

        jListTemasFavoritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneTemasFavoritos.setViewportView(jListTemasFavoritos);

        jListAlbumesFavoritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneAlbumesFavoritos.setViewportView(jListAlbumesFavoritos);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(ImageClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecNac)
                            .addComponent(jLabelNickname)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelApellido)
                            .addComponent(jLabelCorreo))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNicknameInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelApellidoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFecNacInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCorreoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabelTituloSeguidores))
                            .addComponent(jScrollPaneSeguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneListasRFavoritas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelTituloListasFavoritas)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabelTituloSeguidos))
                                    .addComponent(jScrollPaneSeguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabelTituloListasCreadas))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jScrollPaneListasRCreadas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTituloAlbumesFavoritos)
                                    .addComponent(jScrollPaneAlbumesFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPaneTemasFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabelTituloTemasFavoritos))))))
                    .addComponent(jLabel)
                    .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNickname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNicknameInfo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelNombreInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellido)
                            .addComponent(jLabelApellidoInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFecNac)
                            .addComponent(jLabelFecNacInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCorreo)
                            .addComponent(jLabelCorreoInfo)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ImageClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTituloListasCreadas)
                    .addComponent(jLabelTituloSeguidos)
                    .addComponent(jLabelTituloSeguidores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneSeguidores)
                    .addComponent(jScrollPaneListasRCreadas)
                    .addComponent(jScrollPaneSeguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel)
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTituloListasFavoritas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneListasRFavoritas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTituloAlbumesFavoritos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneAlbumesFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelTituloTemasFavoritos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneTemasFavoritos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jScrollPane.setViewportView(jPanel);

        jLabelTituloDatos.setFont(new java.awt.Font("Liberation Sans", 1, 21)); // NOI18N
        jLabelTituloDatos.setText("DATOS DEL CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeleccioneCliente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPaneListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAceptar)))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabelTituloDatos)
                        .addGap(259, 259, 259))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeleccioneCliente)
                    .addComponent(jLabelTituloDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneListClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAceptar))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(356, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        
        // Obtengo el Nickname seleccionado
        String nicknameClienteSeleccionado = jListClientes.getSelectedValue();
        
        Fabrica fb = Fabrica.getInstance();
        controlador = fb.getControlador();
        
        // Obtengo sus datos
        DTDatosCliente datosCliente = controlador.ConsultarPerfilCliente(nicknameClienteSeleccionado);
        
        // Verificar si hay una selección
        if (nicknameClienteSeleccionado != null) {
            
            jLabelNicknameInfo.setText(datosCliente.getNickname());
            jLabelNombreInfo.setText(datosCliente.getNombreUsuario());
            jLabelApellidoInfo.setText(datosCliente.getApellidoUsuario());
            
            // Convertir Date a formato String
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String fecNacString = dateFormat.format(datosCliente.getFecNac());
            jLabelFecNacInfo.setText(fecNacString);
            
            jLabelCorreoInfo.setText(datosCliente.getEmail());

            try {
               
                BufferedImage archivoAlmacenado;
                ImageIcon imagen;
                
                // Definir el tamaño deseado de la imagen
                int sizeHorizontal = 156;
                int sizeVertical = 163;
                Image escalaImagen;

                // Verificar si tiene foto de perfil
                if (datosCliente.getFotoPerfil() != null) {
                    
                    // Lee la imagen desde el archivo(ruta)
                    archivoAlmacenado = ImageIO.read(new File(datosCliente.getFotoPerfil()));

                    // Verifica si la imagen se ha cargado correctamante
                    if (archivoAlmacenado != null) {
   
                        // Redimensionar la imagen
                        escalaImagen = archivoAlmacenado.getScaledInstance(sizeHorizontal, sizeVertical, Image.SCALE_SMOOTH);

                        // Convierte archivoAlmacenado a ImageIcon
                        imagen = new ImageIcon(escalaImagen);

                        ImageClienteLabel.setIcon(imagen);
                        ImageClienteLabel.setVisible(true);
                    }
                } else { // Asignar foto de perfil predeterminada
                    
                    archivoAlmacenado = ImageIO.read(new File("./Resource/ImagenesPerfil/Default-Photo-Profile.jpg"));
                    
                    // Verifica si la imagen se ha cargado correctamente
                    if (archivoAlmacenado != null) {
                        
                        // Redimensionar la imagen
                        escalaImagen = archivoAlmacenado.getScaledInstance(sizeHorizontal, sizeVertical, Image.SCALE_SMOOTH);
                        
                        // Convierte archivoAlmacenado a ImageIcon
                        imagen = new ImageIcon(escalaImagen);
                        
                        ImageClienteLabel.setIcon(imagen);
                        ImageClienteLabel.setVisible(true);
                    }
                }
                
                
            } catch (IOException e) {
                e.printStackTrace();
            }
                
            
            
            
            /* Recorro lista Nicknames de Seguidores del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nicknames a la JList */
            DefaultListModel<String> listaSeguidores = new DefaultListModel<>();
            ArrayList<String> nicknamesSeguidores = datosCliente.getNicknamesSeguidores();
            
            for (String nickname: nicknamesSeguidores) {
                listaSeguidores.addElement(nickname);
            }
            jListSeguidores.setModel(listaSeguidores);
            
            /* Recorro lista Nicknames de Seguidos del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nicknames a la JList */
            DefaultListModel<String> listaSeguidos = new DefaultListModel<>();
            ArrayList<String> nicknamesSeguidos = datosCliente.getNicknamesSeguidos();
            
            for (String nickname: nicknamesSeguidos) {
                listaSeguidos.addElement(nickname);
            }
            jListSeguidos.setModel(listaSeguidos);
            
            /* Recorro lista ListasR Creadas del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nombres a la JList */
            DefaultListModel<String> listaListasRCreadas = new DefaultListModel<>();
            ArrayList<String> nombresListasRCreadas = datosCliente.getNombresListasRCreadas();
            
            for (String nombreListaC: nombresListasRCreadas) {
                listaListasRCreadas.addElement(nombreListaC);
            }
            jListListasRCreadas.setModel(listaListasRCreadas);
            
            /* Recorro lista ListasR Favoritas del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nombres a la JList */
            DefaultListModel<String> listaListasRFavoritas = new DefaultListModel<>();
            ArrayList<String> nombresListasRFavoritas = datosCliente.getNombresListasRFavoritas();
            
            for (String nombreListaF: nombresListasRFavoritas) {
                listaListasRFavoritas.addElement(nombreListaF);
            }
            jListListasRFavoritas.setModel(listaListasRFavoritas);
            
            /* Recorro lista Albumes Favoritas del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nombres a la JList */
            DefaultListModel<String> listaAlbumesFavoritos = new DefaultListModel<>();
            ArrayList<String> nombresAlbumesFavoritos = datosCliente.getNombresAlbumesFavoritos();
        
            for (String nombreAlbumF: nombresAlbumesFavoritos) {
                listaAlbumesFavoritos.addElement(nombreAlbumF);
            }
            jListAlbumesFavoritos.setModel(listaAlbumesFavoritos);
        
            /* Recorro lista Temas Favoritas del Cliente, 
            mientras que lo agrego como elemento al modelo. Luego 
            setteo el modelo con todos los Nombres a la JList */
            DefaultListModel<String> listaTemasFavoritos = new DefaultListModel<>();
            ArrayList<String> nombresTemasFavoritos = datosCliente.getNombresTemasFavoritos();
            
            for (String nombreTemaF: nombresTemasFavoritos) {
                listaTemasFavoritos.addElement(nombreTemaF);
            }
            jListTemasFavoritos.setModel(listaTemasFavoritos);
            
            // Quito la podibilidad de volver a Consultar
            jButtonAceptar.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void InicializarJLists() {
        DefaultListModel<String> emptyModel = new DefaultListModel<>();
        jListSeguidores.setModel(emptyModel);
        jListSeguidos.setModel(emptyModel);
        jListListasRCreadas.setModel(emptyModel);
        jListListasRFavoritas.setModel(emptyModel);
        jListTemasFavoritos.setModel(emptyModel);
        jListAlbumesFavoritos.setModel(emptyModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageClienteLabel;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellidoInfo;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCorreoInfo;
    private javax.swing.JLabel jLabelFecNac;
    private javax.swing.JLabel jLabelFecNacInfo;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelNicknameInfo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreInfo;
    private javax.swing.JLabel jLabelSeleccioneCliente;
    private javax.swing.JLabel jLabelTituloAlbumesFavoritos;
    private javax.swing.JLabel jLabelTituloDatos;
    private javax.swing.JLabel jLabelTituloListasCreadas;
    private javax.swing.JLabel jLabelTituloListasFavoritas;
    private javax.swing.JLabel jLabelTituloSeguidores;
    private javax.swing.JLabel jLabelTituloSeguidos;
    private javax.swing.JLabel jLabelTituloTemasFavoritos;
    private javax.swing.JList<String> jListAlbumesFavoritos;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListListasRCreadas;
    private javax.swing.JList<String> jListListasRFavoritas;
    private javax.swing.JList<String> jListSeguidores;
    private javax.swing.JList<String> jListSeguidos;
    private javax.swing.JList<String> jListTemasFavoritos;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPaneAlbumesFavoritos;
    private javax.swing.JScrollPane jScrollPaneListClientes;
    private javax.swing.JScrollPane jScrollPaneListasRCreadas;
    private javax.swing.JScrollPane jScrollPaneListasRFavoritas;
    private javax.swing.JScrollPane jScrollPaneSeguidores;
    private javax.swing.JScrollPane jScrollPaneSeguidos;
    private javax.swing.JScrollPane jScrollPaneTemasFavoritos;
    private javax.swing.JSeparator jSeparator;
    // End of variables declaration//GEN-END:variables
}
